import { Employee, AttendanceRecord, LeaveRequest, TaskItem, Announcement, AppNotification } from '../types';
import { DEFAULT_LOGIN_PASSWORD } from '../constants/auth';

export const INITIAL_EMPLOYEES: Employee[] = [
	{
		id: 'emp_001',
		name: 'Hardik',
		email: 'hardik@company.com',
		password: DEFAULT_LOGIN_PASSWORD,
		role: 'employer',
		avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80',
		department: 'Human Resources',
		position: 'HR Director',
		employeeId: 'EMP-001',
		phone: '+1 (555) 234-5678',
		joinDate: '2021-03-15',
		salary: '$115,000 / yr',
		status: 'Active',
		emergencyContact: {
			name: 'Robert Jenkins',
			relationship: 'Spouse',
			phone: '+1 (555) 987-6543',
		},
		leaveBalance: { vacation: 18, sick: 10, casual: 5 },
	},
	{
		id: 'emp_002',
		name: 'Alex Morgan',
		email: 'alex.morgan@company.com',
		password: DEFAULT_LOGIN_PASSWORD,
		role: 'employee',
		avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
		department: 'Engineering',
		position: 'Senior Frontend Engineer',
		employeeId: 'EMP-002',
		phone: '+1 (555) 345-6789',
		joinDate: '2022-01-10',
		salary: '$120,000 / yr',
		status: 'Active',
		emergencyContact: {
			name: 'Julia Morgan',
			relationship: 'Sister',
			phone: '+1 (555) 876-5432',
		},
		leaveBalance: { vacation: 12, sick: 7, casual: 3 },
	},
	{
		id: 'emp_004',
		name: 'Elena Rostova',
		email: 'elena.rostova@company.com',
		password: DEFAULT_LOGIN_PASSWORD,
		role: 'employee',
		avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=250&auto=format&fit=crop&q=80',
		department: 'Design',
		position: 'Senior UI/UX Designer',
		employeeId: 'EMP-004',
		phone: '+1 (555) 567-8901',
		joinDate: '2022-05-18',
		salary: '$95,000 / yr',
		status: 'Active',
		emergencyContact: {
			name: 'Dmitri Rostov',
			relationship: 'Brother',
			phone: '+1 (555) 654-3210',
		},
		leaveBalance: { vacation: 14, sick: 8, casual: 4 },
	},
	{
		id: 'emp_005',
		name: 'David Kim',
		email: 'david.kim@company.com',
		password: DEFAULT_LOGIN_PASSWORD,
		role: 'employee',
		avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80',
		department: 'Marketing',
		position: 'Marketing Strategist',
		employeeId: 'EMP-005',
		phone: '+1 (555) 678-9012',
		joinDate: '2023-02-01',
		salary: '$88,000 / yr',
		status: 'On Leave',
		emergencyContact: {
			name: 'Hannah Kim',
			relationship: 'Mother',
			phone: '+1 (555) 543-2109',
		},
		leaveBalance: { vacation: 5, sick: 2, casual: 1 },
	},
	{
		id: 'emp_006',
		name: 'Priya Patel',
		email: 'priya.patel@company.com',
		password: DEFAULT_LOGIN_PASSWORD,
		role: 'employee',
		avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=250&auto=format&fit=crop&q=80',
		department: 'Finance',
		position: 'Financial Analyst',
		employeeId: 'EMP-006',
		phone: '+1 (555) 789-0123',
		joinDate: '2023-06-15',
		salary: '$92,000 / yr',
		status: 'Active',
		emergencyContact: {
			name: 'Aarav Patel',
			relationship: 'Father',
			phone: '+1 (555) 432-1098',
		},
		leaveBalance: { vacation: 15, sick: 10, casual: 4 },
	},
];

const todayStr = new Date().toISOString().split('T')[0];
const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
	{
		id: 'att_101',
		employeeId: 'emp_002',
		employeeName: 'Alex Morgan',
		date: todayStr,
		clockIn: '08:58 AM',
		status: 'Present',
		notes: 'On time - HQ Office',
	},
	{
		id: 'att_102',
		employeeId: 'emp_003',
		employeeName: 'Marcus Vance',
		date: todayStr,
		clockIn: '09:25 AM',
		status: 'Late',
		notes: 'Traffic delay reported',
	},
	{
		id: 'att_103',
		employeeId: 'emp_004',
		employeeName: 'Elena Rostova',
		date: todayStr,
		clockIn: '09:02 AM',
		status: 'Present',
		notes: 'Remote - Home',
	},
	{
		id: 'att_104',
		employeeId: 'emp_006',
		employeeName: 'Priya Patel',
		date: todayStr,
		clockIn: '08:45 AM',
		status: 'Present',
		notes: 'On time - HQ Office',
	},
	// Yesterday's completed logs
	{
		id: 'att_099',
		employeeId: 'emp_002',
		employeeName: 'Alex Morgan',
		date: yesterdayStr,
		clockIn: '09:00 AM',
		clockOut: '05:30 PM',
		hoursWorked: 8.5,
		status: 'Present',
	},
	{
		id: 'att_100',
		employeeId: 'emp_003',
		employeeName: 'Marcus Vance',
		date: yesterdayStr,
		clockIn: '08:55 AM',
		clockOut: '06:00 PM',
		hoursWorked: 9.08,
		status: 'Present',
	},
];

export const INITIAL_LEAVES: LeaveRequest[] = [
	{
		id: 'lve_201',
		employeeId: 'emp_005',
		employeeName: 'David Kim',
		employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80',
		leaveType: 'Vacation',
		startDate: todayStr,
		endDate: '2026-07-28',
		totalDays: 5,
		reason: 'Annual family summer vacation trip to Hawaii.',
		status: 'Approved',
		managerComment: 'Enjoy your vacation David! Team will cover your campaigns.',
		createdAt: '2026-07-15',
	},
	{
		id: 'lve_202',
		employeeId: 'emp_002',
		employeeName: 'Alex Morgan',
		employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
		leaveType: 'Casual',
		startDate: '2026-07-25',
		endDate: '2026-07-26',
		totalDays: 2,
		reason: 'Attending regional React Native tech conference.',
		status: 'Pending',
		createdAt: '2026-07-20',
	},
	{
		id: 'lve_203',
		employeeId: 'emp_004',
		employeeName: 'Elena Rostova',
		employeeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=250&auto=format&fit=crop&q=80',
		leaveType: 'Sick',
		startDate: '2026-07-30',
		endDate: '2026-07-30',
		totalDays: 1,
		reason: 'Medical checkup appointment and blood work.',
		status: 'Pending',
		createdAt: '2026-07-21',
	},
	{
		id: 'lve_204',
		employeeId: 'emp_006',
		employeeName: 'Priya Patel',
		employeeAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=250&auto=format&fit=crop&q=80',
		leaveType: 'Casual',
		startDate: '2026-07-02',
		endDate: '2026-07-03',
		totalDays: 2,
		reason: 'Personal home renovation inspection.',
		status: 'Approved',
		managerComment: 'Approved by Sarah.',
		createdAt: '2026-06-28',
	},
];

export const INITIAL_TASKS: TaskItem[] = [
	{
		id: 'tsk_301',
		title: 'Upgrade Expo Router & Web Navigation',
		description: 'Ensure smooth tab navigation across iOS, Android, and Web platforms with universal routing.',
		assignedToId: 'emp_002',
		assignedToName: 'Alex Morgan',
		assignedToAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
		createdById: 'emp_001',
		createdByName: 'HARDIK',
		dueDate: '2026-07-24',
		priority: 'High',
		status: 'In Progress',
		category: 'Engineering',
		createdAt: '2026-07-19',
	},
	{
		id: 'tsk_302',
		title: 'Q3 Product Roadmap Review',
		description: 'Finalize core features, timeline milestones, and developer allocation for Q3 deliverables.',
		assignedToId: 'emp_003',
		assignedToName: 'Marcus Vance',
		assignedToAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
		createdById: 'emp_001',
		createdByName: 'HARDIK',
		dueDate: '2026-07-26',
		priority: 'Urgent',
		status: 'Pending',
		category: 'Product',
		createdAt: '2026-07-20',
	},
	{
		id: 'tsk_303',
		title: 'Mobile App Design System Specs',
		description: 'Create Figma design system components for buttons, input fields, badges, and dark/light mode cards.',
		assignedToId: 'emp_004',
		assignedToName: 'Elena Rostova',
		assignedToAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=250&auto=format&fit=crop&q=80',
		createdById: 'emp_001',
		createdByName: 'HARDIK',
		dueDate: '2026-07-22',
		priority: 'Medium',
		status: 'Completed',
		category: 'Design',
		createdAt: '2026-07-17',
	},
	{
		id: 'tsk_304',
		title: 'Quarterly Financial Audit Report',
		description: 'Prepare balance sheets, OPEX summaries, and revenue forecasts for board meeting.',
		assignedToId: 'emp_006',
		assignedToName: 'Priya Patel',
		assignedToAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=250&auto=format&fit=crop&q=80',
		createdById: 'emp_001',
		createdByName: 'HARDIK',
		dueDate: '2026-07-29',
		priority: 'High',
		status: 'In Progress',
		category: 'Finance',
		createdAt: '2026-07-18',
	},
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
	{
		id: 'ann_401',
		title: '🎉 Annual Tech Retreat Announcement',
		content: 'We are thrilled to announce our 2026 Annual Team Retreat will take place in Lake Tahoe this September! All accommodation and travel will be sponsored by the company.',
		category: 'Event',
		authorName: 'HARDIK',
		authorRole: 'HR Director',
		authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
		isPinned: true,
		createdAt: '2026-07-20',
	},
	{
		id: 'ann_402',
		title: '📢 Updated Flexible Working Policy',
		content: 'Effective next Monday, core working hours are officially set from 10 AM to 4 PM local time. Remote flexibility remains 3 days per week for all departments.',
		category: 'Policy Update',
		authorName: 'HARDIK',
		authorRole: 'HR Director',
		authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
		isPinned: true,
		createdAt: '2026-07-18',
	},
	{
		id: 'ann_403',
		title: '⚡ Server Maintenance Window Scheduled',
		content: 'Our internal staging servers will undergo routine maintenance this Saturday from 2:00 AM to 5:00 AM UTC. Expect minor intermittent API interruptions.',
		category: 'Urgent',
		authorName: 'Alex Morgan',
		authorRole: 'Senior Frontend Engineer',
		authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
		isPinned: false,
		createdAt: '2026-07-15',
	},
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
	{
		id: 'not_501',
		userId: 'emp_002',
		title: 'New Task Assigned',
		message: 'HARDIK assigned you "Upgrade Expo Router & Web Navigation".',
		type: 'task',
		isRead: false,
		createdAt: '2026-07-19',
	},
	{
		id: 'not_502',
		userId: 'emp_001',
		title: 'New Leave Request',
		message: 'Alex Morgan applied for 2 days Casual Leave.',
		type: 'leave',
		isRead: false,
		createdAt: '2026-07-20',
	},
];
